services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    networks:
      - pg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ny_taxi"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pg-network
    depends_on:
      pgdatabase:
        condition: service_healthy

  ingest:
    image: taxi_ingest:v001
    depends_on:
      pgdatabase:
        condition: service_healthy
    networks:
      - pg-network
    command:
      - --pg-user=root
      - --pg-pass=root
      - --pg-host=pgdatabase
      - --pg-port=5432
      - --pg-db=ny_taxi
      - --target-table=yellow_taxi_trips_2021_2
      - --year=2021
      - --month=2
      - --chunksize=100000
    profiles: ["ingest"]

networks:
  pg-network:
    name: pg-network

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:
